name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SH_KEY }}

          script: |
            cd /var/www/eshop
            git pull origin dev
            nerdctl compose down
            nerdctl compose build
            nerdctl compose up -d