name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r backend/requirements.txt

      - name: Python syntax check
        run: python -m compileall backend
